### ISSUE TITLE
dvmt and cfg

### ISSUE THREAD

**Issue by cansozbir** [shangyuan0818/DELL_INSPIRON_5401_OPENCORE#1]
Hello,
I have never installed a Hackintosh, sorry from now if I am asking a ridiculous question :)
I have a Dell Inspiron 5401 1035g1 i5 version. I need to install Hackintosh on it. I have found Lorys89's [repo](https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE) first and your repo second. 
In his repo, he is doing some CPU configurations on bios, but you are not doing it. I was searching for alternatives to it because I don't want to brick my laptop. I think there is a patch for ice lake iGPUs on Opencore, I have read that on this [link](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/
).
Did you include this patch in your repo and will it use iGPU acceleration? So I will not need to edit anything on bios. 
Thanks for your great effort. I am waiting for a response from you :)

**Comment by cansozbir** [comment]
I installed this version, I just installed an extra kext for my wifi card. And that is it, I didn't do anything for dvmt prealloc. 
It uses igpu acceleration. No issues at all.

**Comment by shangyuan0818** [comment]
That's perfect, if you don't have any problems, then you don't need to change anything(include dvmt). Check if you can close your lid to make macOS sleep perfectly. If you can't then it must has some problems with dGPU(you can change the "SSDT-dGPU-Off" and block them).
